### PR TITLE
Added wiselinks_description to be more SEO friendly

### PR DESCRIPTION
**Pull request by cfiorini**
in one of my project i have a listing with filters that change results and i need that also meta description gets change during updates

### CODE REVIEW

**Comment by PikachuEXE** [comment]
Does crawler execute AJAX and get the description?

PR looks good to me.

**Comment by igor-alexandrov** [comment]
Don't think that crawler execute AJAX. But this may be helpful to services like Google Analytics and Yandex Metrika, that may post page SEO params with user data.

Will merge this on holidays. Thanks!

**Comment by PikachuEXE** [comment]
I see :)

**Comment by cfiorini** [comment]
i did this implementation after  this post http://www.bing.com/blogs/site_blogs/b/webmaster/archive/2013/03/21/search-engine-optimization-best-practices-for-ajax-urls.aspx 
and this video https://www.youtube.com/watch?v=yiAF9VdvRPw 

please let me know what do you think 

thanks

**Comment by igor-alexandrov** [comment]
Merged to 1.2.1. Thanks!

**Pull request merged**
