### PR TITLE
fixed 304 Not Modified response parsing

### PR DESCRIPTION
**Pull request by aishek**
This fixes content parsing when browser takes local cached full html as server's response (in case of 304 Not Modified answer from server)

### CODE REVIEW

**Comment by PikachuEXE** [comment]
:thumbsup:

**Comment by PikachuEXE** [comment]
Wait, just test on an app, will got `History.js Adapter has already been loaded...`

**Comment by aishek** [comment]
@PikachuEXE could you show code?

**Comment by PikachuEXE** [comment]
Sorry seems the JS loaded is outdated (even after app restart and page refresh)
`window._Wiselinks.Response` is `undefined`
I use 

``` ruby
gem 'wiselinks', github: 'aishek/wiselinks', branch: '304-http-issue'
```

Am I wrong?

**Comment by aishek** [comment]
@PikachuEXE I'm not sure :) May I see app code?

**Comment by PikachuEXE** [comment]
I guess `Chrome` use cached version of HTML (But I see `200` in response...)
I try with `Incognito Window` then it loads the correct version of JS

OK it works as expected (with full page response)

**Comment by aishek** [comment]
@PikachuEXE give me a URL?

**Comment by PikachuEXE** [comment]
I was testing locally :o

**Comment by aishek** [comment]
@PikachuEXE ok, I'll answer later

**Comment by PikachuEXE** [comment]
I said all works as expected :P

**Comment by aishek** [comment]
Oh, understand %) Yeah, it was cached version of JS at client side. @igor-alexandrov MERGE THIS REQUEST NOW!!!!111111

**Comment by PikachuEXE** [comment]
@igor-alexandrov We really need this PR...

**Comment by PikachuEXE** [comment]
@igor-alexandrov PING!

**Comment by igor-alexandrov** [comment]
Guys, this PR breaks the idea of Wiselinks as it always load full document from server, then parses it and uses only needed part. This is not how Wiselinks works now and not how it should work.

I don't think that it can be merged in its current state. We should find another way to handle 304 status, but not load full document.

**Comment by aishek** [comment]
This PR does not load full document – it fixes case, when browser returns full document from cache. So the main idea is still untouched, but special technical case get handled. Please, consider again, why not to merge?

**Comment by PikachuEXE** [comment]
==Before==
Normal case: return full page for page request, return partial for wiselink request (server code by developers)
When developer set the page to be cachable: browser use the whole page, insert the whole page (or at least the whole `body` content by default), break things and re run JS (if JS inserted before the end of `body`)

==After==
Normal case: Same as above since that's app code not `wiselinks` code
304 case: Browser use full document cached, so use selector to extract the needed part and insert it

**Comment by igor-alexandrov** [comment]
Ok, git it now.
@aishek please update code of PR to be in same style as all Wiselinks code (I mean `function_name` instead of `functionName`).

Thanks once again!

**Comment by aishek** [comment]
@igor-alexandrov done

**Comment by igor-alexandrov** [comment]
Thanks guys!
Merged to wiselinks-1.2.0!

**Comment by adesakin** [comment]
Is there any conclusion on how to solve this issue?

**Comment by PikachuEXE** [comment]
Why discuss an issue in a merged PR?
Now I am not even sure what is issue being discussed...

**Pull request merged**
