### PR TITLE
Remove encodeURI in RequestManager for compare urls

### PR DESCRIPTION
**Pull request by faustman**
Hello!

i found some bug.

``` ruby
encodeURI(url) != url
```

### CODE REVIEW

**Comment by faustman** [comment]
Hey! Its not my fail.. What do I do?

**Comment by igor-alexandrov** [comment]
Can you tell why exactly we should not encode URL? It was done to handle correctly non ASCII values in form and link params.

**Comment by igor-alexandrov** [comment]
Got it! Fixed in wiselinks-0.7.3.
Thanks!

**Comment by faustman** [comment]
:thumbsup: Thanks!

**Pull request closed without merging**
