### PR TITLE
Fix events url variable

### PR DESCRIPTION
**Pull request by incubus**

### CODE REVIEW

**Comment by igor-alexandrov** [comment]
I don't think that you are right here. Is there any purpose to send complete `state` to event?

**Comment by incubus** [comment]
Agree, I just want to send the url variable. But that is your code. :)

``` ruby
  _done: ($target, status, state, data) ->
    $(document).trigger('page:done', [$target, status, state.url, data])

  _fail: ($target, status, state, error) ->
    $(document).trigger('page:fail', [$target, status, state.url, error])

  _always: ($target, status, state) ->
    $(document).trigger('page:always', [$target, status, state.url])
```

**Comment by igor-alexandrov** [comment]
And what is wrong with it? The only way to fetch right URL is to fetch it from `state.url`.

**Comment by incubus** [comment]
I just fix a typo. You send state.url to the function and use state.url again into it. Please take a look on my pull request. :)

**Comment by incubus** [comment]
Here is another version of the fix.

**Comment by igor-alexandrov** [comment]
:+1:
Wow! I see now!

Will be merged today.

**Comment by igor-alexandrov** [comment]
Done in wiselinks-0.7.0.
Thanks!

**Pull request merged**
